import { hash as argonHash } from '@node-rs/argon2'
import { mintManageToken } from '../lib/token-crypto.js'
import { PrismaClient } from './generated/client.js'
import { PrismaPg } from '@prisma/adapter-pg'
import { computeSlots } from '../lib/domain/availability.js'
import { bookingWindows, REFERENCE_ALPHABET } from '../lib/domain/policy.js'
import type { Interval } from '../lib/domain/interval.js'
import {
  wallToUtc,
  parseIsoDate,
  shiftIsoDate,
  isoDateInZone,
  localMidnightUtc,
  dayOfWeekInZone,
} from '../lib/time.js'

/**
 * Realistic demo data for Glow & Grace.
 *
 * Bookings are not hard-coded times. They are generated by running the real
 * `computeSlots()` against each therapist's working rules and time off, then booking into
 * slots it returns — with every booking created so far fed back in as blocked time. That
 * means the seed cannot produce a booking the exclusion constraint would reject, and
 * seeding doubles as an end-to-end exercise of the availability engine.
 *
 *   npm run db:seed
 */

const TZ = 'Asia/Karachi'
const DEV_PASSWORD = 'ChangeMe123!'

const db = new PrismaClient({
  adapter: new PrismaPg({ connectionString: process.env.DATABASE_URL }),
  log: ['error'],
})

/** Deterministic PRNG so re-seeding produces the same schedule. */
function mulberry32(seed: number) {
  return () => {
    seed |= 0
    seed = (seed + 0x6d2b79f5) | 0
    let t = Math.imul(seed ^ (seed >>> 15), 1 | seed)
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296
  }
}
const rand = mulberry32(20260824)

function pick<T>(items: readonly T[]): T {
  return items[Math.floor(rand() * items.length)]
}

function reference(): string {
  let out = ''
  for (let i = 0; i < 6; i++) {
    out += REFERENCE_ALPHABET[Math.floor(rand() * REFERENCE_ALPHABET.length)]
  }
  return `BK-${out}`
}

// Manage tokens come from lib/token-crypto.ts: hashed for lookup, encrypted so later
// emails can rebuild the customer's link.

// ── the business ─────────────────────────────────────────────────────────────

const BIZ = 'biz_noor'

const SERVICES = [
  { id: 'svc_signature_facial', slug: 'signature-facial', name: 'Signature Facial', durationMins: 60, bufferAfterMins: 15, priceMinor: 8500 },
  { id: 'svc_deep_tissue', slug: 'deep-tissue-massage', name: 'Deep Tissue Massage', durationMins: 90, bufferAfterMins: 15, priceMinor: 12000 },
  { id: 'svc_express_glow', slug: 'express-glow', name: 'Express Glow Facial', durationMins: 30, bufferAfterMins: 10, priceMinor: 4500 },
  { id: 'svc_consultation', slug: 'skin-consultation', name: 'Skin Consultation', durationMins: 30, bufferAfterMins: 0, priceMinor: 3000 },
] as const

const STAFF = [
  { id: 'stf_ayesha', slug: 'ayesha-mirza', name: 'Ayesha Mirza', days: [1, 2, 3, 4, 5, 6], services: ['svc_signature_facial', 'svc_express_glow', 'svc_consultation'] },
  { id: 'stf_hina', slug: 'hina-raza', name: 'Hina Raza', days: [2, 3, 4, 5, 6], services: ['svc_deep_tissue'] },
  { id: 'stf_sana', slug: 'sana-qureshi', name: 'Sana Qureshi', days: [1, 3, 5, 6], services: ['svc_signature_facial', 'svc_express_glow'] },
] as const

/**
 * Weekly hours as minutes from local midnight. Weekdays are split around a lunch break,
 * which is the FR-A6 case — several rows per day, not one span.
 */
function rulesFor(dayOfWeek: number): { startMin: number; endMin: number }[] {
  if (dayOfWeek === 0) return [] // Sunday, closed
  if (dayOfWeek === 6) return [{ startMin: 600, endMin: 960 }] // Sat 10:00–16:00
  return [
    { startMin: 600, endMin: 780 }, // 10:00–13:00
    { startMin: 840, endMin: 1140 }, // 14:00–19:00
  ]
}

const CUSTOMERS = [
  { name: 'Fatima Sheikh', email: 'Fatima.Sheikh@example.com', phone: '+92 300 1234567' },
  { name: 'Zainab Ali', email: 'zainab.ali@example.com', phone: '+92 301 2345678' },
  { name: 'Maryam Khan', email: 'MARYAM.KHAN@example.com', phone: '+92 302 3456789' },
  { name: 'Hooria Baig', email: 'hooria@example.com', phone: '+92 303 4567890' },
  { name: 'Rida Anwar', email: 'rida.anwar@example.com', phone: '+92 304 5678901' },
  { name: 'Nida Farooq', email: 'nida.f@example.com', phone: '+92 305 6789012' },
] as const

const NOTES = [
  null,
  null,
  null,
  'Sensitive skin — please patch test.',
  'Prefer a quiet room if possible.',
  'Running slightly late is likely, coming from work.',
  null,
]

async function wipe() {
  await db.notificationLog.deleteMany({})
  await db.bookingHistory.deleteMany({})
  await db.booking.deleteMany({})
  await db.auditLog.deleteMany({})
  await db.timeOff.deleteMany({})
  await db.availabilityRule.deleteMany({})
  await db.user.deleteMany({})
  await db.serviceStaff.deleteMany({})
  await db.customer.deleteMany({})
  await db.service.deleteMany({})
  await db.staff.deleteMany({})
  await db.business.deleteMany({})
}

async function main() {
  console.log('\nSeeding Glow & Grace…\n')
  await wipe()

  // ── business ───────────────────────────────────────────────────────────────
  await db.business.create({
    data: {
      id: BIZ,
      name: 'Glow & Grace',
      timezone: TZ,
      currency: 'PKR',
      currencyDecimals: 0, // PKR has no circulating minor unit [C1]
      slotIntervalMins: 15,
      minLeadTimeMins: 120,
      bookingWindowDays: 60,
      cancelWindowHours: 24,
    },
  })

  await db.service.createMany({
    data: SERVICES.map((s, i) => ({
      id: s.id,
      businessId: BIZ,
      name: s.name,
      slug: s.slug,
      durationMins: s.durationMins,
      bufferBeforeMins: 0,
      bufferAfterMins: s.bufferAfterMins,
      priceMinor: s.priceMinor,
      sortOrder: i,
      // One service requires approval, so PENDING is reachable in the demo [B4].
      requiresApproval: s.id === 'svc_consultation',
    })),
  })

  await db.staff.createMany({
    data: STAFF.map((s, i) => ({
      id: s.id,
      businessId: BIZ,
      name: s.name,
      slug: s.slug,
      sortOrder: i,
    })),
  })

  await db.serviceStaff.createMany({
    data: STAFF.flatMap((s) => s.services.map((serviceId) => ({ serviceId, staffId: s.id }))),
  })

  await db.availabilityRule.createMany({
    data: STAFF.flatMap((s) =>
      s.days.flatMap((day) =>
        rulesFor(day).map((r) => ({ staffId: s.id, dayOfWeek: day, ...r })),
      ),
    ),
  })

  // ── users ──────────────────────────────────────────────────────────────────
  const passwordHash = await argonHash(DEV_PASSWORD)
  await db.user.create({
    data: { email: 'owner@glowandgrace.example', passwordHash, role: 'ADMIN' },
  })
  for (const s of STAFF) {
    await db.user.create({
      data: {
        email: `${s.slug.split('-')[0]}@glowandgrace.example`,
        passwordHash,
        role: 'STAFF',
        staffId: s.id,
      },
    })
  }

  // ── customers ──────────────────────────────────────────────────────────────
  const customers = []
  for (const c of CUSTOMERS) {
    customers.push(
      await db.customer.create({
        data: {
          businessId: BIZ,
          name: c.name,
          email: c.email,
          // Lowercased identity key, so casing never splits one person in two [C2].
          emailNorm: c.email.trim().toLowerCase(),
          phone: c.phone,
        },
      }),
    )
  }

  // ── time off ───────────────────────────────────────────────────────────────
  const today = isoDateInZone(TZ, new Date())
  const leaveStart = shiftIsoDate(today, 5)
  const leaveEnd = shiftIsoDate(today, 8)
  const closureDay = shiftIsoDate(today, 3)

  const timeOff: { staffId: string | null; interval: Interval }[] = [
    {
      staffId: 'stf_sana',
      interval: {
        start: localMidnightUtc(TZ, leaveStart),
        end: localMidnightUtc(TZ, leaveEnd),
      },
    },
    {
      staffId: null, // whole business closed
      interval: {
        start: atLocal(closureDay, 14 * 60),
        end: atLocal(closureDay, 19 * 60),
      },
    },
  ]

  for (const t of timeOff) {
    await db.timeOff.create({
      data: {
        businessId: BIZ,
        staffId: t.staffId,
        startsAt: t.interval.start,
        endsAt: t.interval.end,
        reason: t.staffId ? 'Annual leave' : 'Staff training — closed',
      },
    })
  }

  // ── bookings, generated from real availability ─────────────────────────────
  //
  // Every booking created is fed back in as blocked time, so the next call to
  // computeSlots() already knows about it. The exclusion constraint therefore never
  // has anything to reject — which is the point.
  const blockedByStaff = new Map<string, Interval[]>(STAFF.map((s) => [s.id, []]))
  for (const t of timeOff) {
    for (const s of STAFF) {
      if (t.staffId === null || t.staffId === s.id) blockedByStaff.get(s.id)!.push(t.interval)
    }
  }

  let created = 0
  let pastCount = 0

  for (let offset = -7; offset <= 14; offset++) {
    const date = shiftIsoDate(today, offset)
    const dow = dayOfWeekInZone(TZ, localMidnightUtc(TZ, date))
    const isPast = offset < 0

    for (const staff of STAFF) {
      if (!(staff.days as readonly number[]).includes(dow)) continue

      const working = rulesFor(dow).map((r) => ({
        start: atLocal(date, r.startMin),
        end: atLocal(date, r.endMin),
      }))
      if (working.length === 0) continue

      // Two or three appointments a day each — a believable book, not a full one.
      const target = 2 + Math.floor(rand() * 2)

      for (let n = 0; n < target; n++) {
        // Pick once. Calling pick() inside the predicate re-rolls on every iteration.
        const serviceId = pick(staff.services)
        const service = SERVICES.find((s) => s.id === serviceId)!
        const blocked = blockedByStaff.get(staff.id)!

        const slots = computeSlots({
          working,
          blocked,
          durationMins: service.durationMins,
          bufferBeforeMins: 0,
          bufferAfterMins: service.bufferAfterMins,
          stepMins: 15,
          gridAnchor: localMidnightUtc(TZ, date),
          // The seed writes history as well as future, so policy bounds are wide open
          // here. Real booking creation applies them; this is not that path.
          earliest: new Date('1970-01-01T00:00:00Z'),
          latest: new Date('2100-01-01T00:00:00Z'),
        })
        if (slots.length === 0) break

        const startsAt = slots[Math.floor(rand() * slots.length)]
        const windows = bookingWindows(
          startsAt,
          service.durationMins,
          0,
          service.bufferAfterMins,
        )

        const roll = rand()
        const status = isPast
          ? roll < 0.88
            ? 'COMPLETED'
            : 'NO_SHOW'
          : service.id === 'svc_consultation' && roll < 0.3
            ? 'PENDING'
            : roll < 0.94
              ? 'CONFIRMED'
              : 'CANCELLED'

        const customer = pick(customers)
        const token = mintManageToken()

        await db.booking.create({
          data: {
            businessId: BIZ,
            serviceId: service.id,
            staffId: staff.id,
            customerId: customer.id,
            reference: reference(),
            manageTokenHash: token.hash,
            manageTokenCipher: token.cipher,
            manageTokenExpiresAt: new Date(windows.endsAt.getTime() + 30 * 864e5),
            startsAt: windows.startsAt,
            endsAt: windows.endsAt,
            blockStartsAt: windows.blockStartsAt,
            blockEndsAt: windows.blockEndsAt,
            durationMins: service.durationMins,
            bufferBeforeMins: 0,
            bufferAfterMins: service.bufferAfterMins,
            priceMinor: service.priceMinor,
            currency: 'PKR',
            status,
            customerNote: pick(NOTES),
            cancelledAt: status === 'CANCELLED' ? new Date() : null,
            cancelReason: status === 'CANCELLED' ? 'Something came up' : null,
          },
        })

        // Only PENDING and CONFIRMED hold time — the same predicate as the constraint.
        if (status === 'PENDING' || status === 'CONFIRMED') {
          blocked.push({ start: windows.blockStartsAt, end: windows.blockEndsAt })
        }

        created++
        if (isPast) pastCount++
      }
    }
  }

  // ── summary ────────────────────────────────────────────────────────────────
  const counts = await db.booking.groupBy({ by: ['status'], _count: true })

  console.log(`  business    Glow & Grace (${TZ}, PKR)`)
  console.log(`  services    ${SERVICES.length}`)
  console.log(`  staff       ${STAFF.length}`)
  console.log(`  rules       ${await db.availabilityRule.count()} (split shifts w/ lunch)`)
  console.log(`  time off    ${timeOff.length} (1 staff leave, 1 business closure)`)
  console.log(`  customers   ${customers.length}`)
  console.log(`  bookings    ${created}  (${pastCount} in the past)`)
  for (const c of counts.sort((a, b) => b._count - a._count)) {
    console.log(`                ${String(c._count).padStart(3)}  ${c.status}`)
  }
  console.log(`\n  admin login  owner@glowandgrace.example  /  ${DEV_PASSWORD}`)
  console.log(`  today is     ${today} (${TZ})\n`)

  await db.$disconnect()
}

/** A UTC instant from a local date and minutes-from-midnight in the business zone. */
function atLocal(isoDate: string, minutes: number): Date {
  const { year, month, day } = parseIsoDate(isoDate)
  return wallToUtc(TZ, year, month, day, minutes).instant
}

main().catch(async (e) => {
  console.error(e)
  await db.$disconnect()
  process.exit(1)
})
